### ISSUE TITLE
Compatibility issue with KitKat (and possibly other versions)

### ISSUE THREAD

**Issue by pablode** [ahmedrizwan/SeekBarCompat#4] opened 2015-07-07 19:19 UTC
Hello. I would like to integrate this library into my app (https://play.google.com/store/apps/details?id=com.pablode.labeledmusicplayer), however I ran into some compatibility issues with older android versions, more specifically KitKat (haven't tested other ones).

![s1](https://cloud.githubusercontent.com/assets/3663466/8554741/b5bc328c-24eb-11e5-8f1e-23dae265578f.png)

Basically, screenshot 1 shows how it SHOULD look. This is a screenshot of android 22 (htc one,  cyanogenmod, newest version), however I can confirm that it also works on 21 (nexus 9, stock android). Additionally, this is how it looks when using the native seekbar provided by android (but obviously I don't want to use that, since I want the material style on every device, which this library tries to provide).

![s2](https://cloud.githubusercontent.com/assets/3663466/8554857/a58516da-24ec-11e5-903d-b6bfbaed067f.png)

Screenshot 2 shows how the use of the library actually looks in an emulator of KitKat, API level 19. On the left side is the corresponding code. There is programmatical interaction, but only for setting thumb color/alpha, enabling/disabling it and bringing the view to the front.

I can provide you with more code, if needed, however I suppose it won't be relevant. 

It would be awesome if you were to fix this. Thanks.

**Comment by ahmedrizwan** [comment] 2015-07-07 19:34
Oh Ok. Yes, it's actually a problem with the base SeekBar class - so I couldn't fix it programmatically. 
The solution is to just add android:maxHeight attribute, let's say android:maxHeight="300sp" 
It'll fix the gravity/positioning of the thumb on all APIs.
Do try and let me know if it works. Thanks!

**Comment by pablode** [comment] 2015-07-07 21:05
![s3](https://cloud.githubusercontent.com/assets/3663466/8556916/4fb20b1a-24fa-11e5-9b3a-2d591ced6876.jpg)

Your're right, but it only fixes a part of the issue. I set it to 300dp, out of curiosity, and the thumb is now being displayed correctly. However, as you probably can notice, there is an unwanted offset to the bar. It's supposed to be 1dp or 2dp higher, that's my guess (if you look at the code, there is a -16dp offset to the bottom). 
My guess is that the seekbar view itself is shorter in height than on lollipop. This might be depending on the drawable used. Because it's short and since the bottom side is being pulled down 16dp, the center of the SeekBar is too low and not where it's supposed to be.
It sound like it could be potentially fixed by adjusting the size, but if that's not the case I could try to move the view to its center programmatically.

**Comment by ahmedrizwan** [comment] 2015-07-07 21:32
Yea you're right! It'll be fixed in the next release (by tomorrow) as I'm making a lot of implementation changes (right now). For a very "temporary" solution, I'd recommend that you create two different layouts for API 21 and below. For 21, keep the -16dp margin and for lower APIs - try -14 or -13dp. Use this workaround for now - I'll update you as soon as I am done with the fix. Thanks!

**Comment by pablode** [comment] 2015-07-07 21:50
That's awesome! Actually, the application uses the native SeekBar for now, but I guess I'll switch to this library once all the issues have been resolved. I'll simply put the git branch on hold for now. I'll check out the progress you made in a few days and keep you up-to-date if I experience another issue in future releases. Thank you for being so cooperative:)

**Comment by ahmedrizwan** [comment] 2015-07-09 01:45
No problem Pablode! :) 
I've updated the library - use version 0.2.0 to get the latest update.
The update fixes all the issues related to margin, positioning - and no maxHeight needed anymore :P 
And I've also extended the support to also include API 14 and 15.
Do check, and let me know if it's working. Thanks!

**Comment by pablode** [comment] 2015-07-09 13:58
Hi! I just tested version 0.2.0 and most of the problems have been resolved :) 
However, unfortunately, there is a new one:

![s4](https://cloud.githubusercontent.com/assets/3663466/8596909/70f05300-2652-11e5-9b12-a25d1facb87f.jpg)

The thumb does not stay in front of the progress bar, although it moves with it. At the start it works, however the width between both components gets wider with the progress it makes. If you can't reproduce the issue, I might be able to give you more information about the circumstances.

**Comment by ahmedrizwan** [comment] 2015-07-09 14:00
Ok - yeah, I thought I solved this issue before updating the library :P, but let me check what could be causing it.

**Comment by ahmedrizwan** [comment] 2015-07-09 14:17
I can't seem to reproduce it, can you share the layout specs?

**Comment by Pablode** [comment] 2015-07-10 11:39
![s5](https://cloud.githubusercontent.com/assets/3663466/8617828/fc7c3d8e-2707-11e5-8944-92e8a0473210.png)

This is every call related to the SeekBar. However I don't think that this will be useful, so I retrieved some values at runtime. When I remember right, the duration and progress of audio is measured and stored in milliseconds. On update (20 times a second), the values for the SeekBar are being adjusted.
Try setMax(103610) and setProgress(55576), maybe it will reproduce the issue.

It should also be noted that the progress bar is the actual representation of the progress and the thumb is offset, not the other way around.

**Comment by pablode** [comment] 2015-07-10 11:51
Actually, I just found the cause of the issue.

``` java
        <app.minimize.com.seek_bar_compat.SeekBarCompat
            android:id="@+id/audioseekbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_above="@id/appbar"
            android:layout_marginBottom="-16dp"
            android:elevation="12dp"
            android:padding="0dp"
            app:progressColor="@color/colorAccent"
            app:progressBackgroundColor="@color/transparent"
            app:thumbColor="@color/colorAccent" />
```

It's the android:padding="0dp".

**Comment by ahmedrizwan** [comment] 2015-07-10 14:03
Yeah I didn't take padding into account - as I'm calculating the thumb position manually. 
Anyway I'm working on it, and it'll soon be resolved. Thanks for pointing it out. :)

**Comment by pablode** [comment] 2015-07-10 14:12
Awesome. My app also sets the alpha value of the thumb and I don't know if that's possible using this library right now. It should be easy to implement support down to API level 16. I don't know about versions below 16 since, to my knowledge, getThumb() might not be available.

**Comment by ahmedrizwan** [comment] 2015-07-10 19:02
Yeah setting alpha will work on all APIs because it's a custom thumb implementation (from scratch) so it's not dependent on API levels. I'll add that too. 
I'm close on solving the padding issue. Will update you once done! :)

**Comment by pablode** [comment] 2015-07-10 19:15
Thank you. Actually, the only reason why I released my app with minSDK 16 is because of that alpha issue. Now I could potentially go down to 14, which is pretty cool.

**Comment by ahmedrizwan** [comment] 2015-07-21 10:58
Sorry I'm a bit late, but I've finally updated the library.
Please update to 0.2.1 version. I have solved the padding and speeding issue, do make sure to specify _maxHeight_ attribute for proper thumb gravity. 
And I have added a method called setThumbAlpha(), which you can use if you need to change alpha. 
Thanks!

**Closed as completed by ahmedrizwan** 2015-07-21 10:58 UTC

**Comment by pablode** [comment] 2015-07-24 22:07
Thanks for updating the library. All the styling issues have been resolved, however something is still not working how I would like it to work - the fix should be simple though.
Basically I'm not able to set the thumb alpha value below Lollipop.

``` java
@TargetApi(Build.VERSION_CODES.JELLY_BEAN)
    public void setThumbAlpha(int alpha) {
        mAlpha = alpha;
        if (lollipopAndAbove())
            getThumb().setAlpha(mAlpha);
        setLayoutParams(getLayoutParams());
    }
```

This is the code in the library which is not correct. It should provide support down to API level 16, however that's not the case. Rather than calling `lollipopAndAbove()`, it should be `jellybeanOrAbove`, right?

Also, you might want to consider renaming `mAlpha` to `mThumbAlpha` :)

**Comment by ahmedrizwan** [comment] 2015-07-24 23:46
No actually the method works fine, but it currently works only "programmatically" -  I didn't accommodate the XML's alpha (forgot to do that, oops!) - maybe that's why you're not getting the desired results. But thanks! I'll fix this in a few minutes hopefully. :)

**Comment by ahmedrizwan** [comment] 2015-07-25 11:30
I added an attribute called thumbAlpha - you can now set alpha value in XML also. Example is in the Read-me.
Update to version 0.2.3. 
Thanks! :)

**Comment by pablode** [comment] 2015-08-09 19:25
I've just updated to 0.2.3 and tried it out - it seems like all the issues have been resolved. Good job! If you want to include a link to it for some kind of 'library showcase' (probably not), you have my permission.

Oh, and one last thing: Android Studio 1.3 was released and brings a lot of new features. One of them is range annotations, which you could integrate to make using the API easier. More specifically, you could use `@IntRange(from=.., to=..)` for the `setThumbAlpha` method. The function would then look like this: 

```
@TargetApi(Build.VERSION_CODES.JELLY_BEAN)
public void setThumbAlpha(@IntRange(from=0, to=255) int alpha) {
    ...
}
```

Here is some info about this feature:
https://youtu.be/_Rox-HXhRfI?t=1m43s

Also, documentation descriptions for `setThumbAlpha` and `setEnabled` seem to miss. Not that it matters a lot - the function names are self-explaining and the source-code is accessible.

**Comment by ahmedrizwan** [comment] 2015-08-18 21:46
Thank you Pablode - and sorry for the late response, I've been quite busy.
I'm glad the issues were resolved - I mean... pheww! :D 

Yes 'Library Showcase' seems like a good idea! I'll definitely add it!

And thanks for the @IntRrange suggestion - looks extremely useful! I'll incorporate it in the upcoming release.
